Task2
godofevil/nodejs-course pull request #2
Opened 2021-10-29 12:08 UTC by godofevil

Request examples:
curl http://localhost:4000/movie -X POST --data '{"title": "Matrix"}'
curl http://localhost:4000/movie -X GET --data '{"title": "Avatar"}'

2021-11-02 20:30 UTC, rfist requested changes

2021-11-02 20:30 UTC, rfist commented on src/server.ts
> +            log(body ? `${text} ${body}` : 'Movie page')
Well, it's working, but not the best approach. Usually, all GET parameters are passed with URL, so you don't have to parse the body in that case. And probably you will have more routes and methods in the future (PATCH, DELETE) and it can be a problem to manage them with the current code style. I suggest replacing if-else to switch-case and using separate handlers for different routes and methods.

2021-11-02 20:30 UTC, rfist commented on src/server.ts
> +        res.end(message);
Well, it's not like you can not write any logic in the logger - but it's better not to do it. Please, do send a response in proper handlers.

2021-11-03 15:21 UTC, godofevil commented on src/server.ts
> +        res.end(message);
Properly it's not exactly logger, just func to reduce code. Logger as it is in separate file.

2021-11-03 18:56 UTC, rfist requested changes

2021-11-03 18:56 UTC, rfist commented on src/server.ts
> +                body = JSON.parse(data.toString()).title;
It will work only for small request bodies, for requests where you have two or more chunks it will print only the first chunk. You have to collect all data and call parsing on the 'end' event.

2021-11-04 08:29 UTC, godofevil commented on src/server.ts
> +                body = JSON.parse(data.toString()).title;
Yes, thanks, make sence. I fixed it, but get a little stuck, I got correct body in parseBody, but undefined in my handler function. Could you pls manage with this? Seems it's something with async

2021-11-07 09:08 UTC, rfist commented on src/server.ts
> +                body = JSON.parse(data.toString()).title;
It's because `reg.on` do not return Promise, hence node.js doesn't wait for the end callback and call you log function first. You can either wrap `parseBody` function with Promise either move you log to parse function.
```
        .on('end', () => {
            const temp = Buffer.concat(chunks).toString();
            body = JSON.parse(temp);
            log();
            res.end(temp);
        });
```

2021-11-08 20:34 UTC, rfist approved these changes
lgtm

2021-11-09 07:44 UTC, merged